# Generated by Django 5.2.5 on 2025-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom')], default='bride', max_length=100)),
            ],
        ),
    ]
