# Generated by Django 5.2.5 on 2025-09-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='seat_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='tables.table'),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(('seat_number__isnull', False)), fields=('table', 'seat_number'), name='uniq_seat_per_table'),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('table__isnull', True), ('seat_number__isnull', True)), models.Q(('table__isnull', False), ('seat_number__gte', 1), ('seat_number__lte', 10)), _connector='OR'), name='table_and_seat_both_null_or_valid'),
        ),
    ]
