# Generated by Django 5.2.5 on 2025-08-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attending', models.CharField(max_length=10)),
                ('starter', models.CharField(blank=True, max_length=50, null=True)),
                ('main', models.CharField(blank=True, max_length=50, null=True)),
                ('dessert', models.CharField(blank=True, max_length=50, null=True)),
                ('allergies', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
