# Generated by Django 5.2.5 on 2025-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='attending',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='allergy_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='night_before',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('decline', 'Decline')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='wedding_day',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('decline', 'Decline')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='allergies',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
