# Generated by Django 5.2.5 on 2025-12-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_remove_rsvp_attending_rsvp_allergy_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='name',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
